### PR TITLE
Move attribute labels next to point value.

### PR DESCRIPTION
**Pull request by sysrage**
On the attributes screen, the labels are below the point values and it looks odd. This fixes that as well as fixes indentation in _attribute-select.scss.

I have no doubt Koo can improve this, but it looks better than what it was before.

### CODE REVIEW

**Comment by sysrage** [comment]
Test comment.

**Comment by sysrage** [comment]
Testing.

**Comment by sysrage** [comment]
This is a test.

**Comment by sysrage** [comment]
This is a test comment.

**Comment by codecorsair** [comment]
Do you have a photo?

**Comment by sysrage** [comment]
JB pointed out that long values are cut off with these changes. I'll look into a better solution.

**Pull request closed without merging**
