### PR TITLE
UI Widgets

### PR DESCRIPTION
**Pull request by Mehuge**
This PR takes the UI element developed as part of the settings UI and better exposes them so they can be easily re-used.

It also provides a new component `HudNavWindow` to make it easier to implement HudNav UIs.  Given just a UI name, and a function as child that receives a close method, it takes care of the event handling around opening and closing of the UI.

```jsx
<HudNavWindow name='example'>
  {close => <YourUIContent onClose={close}/>}
</HudNavWindow>
```
I also added some documentation for the [UI widgets](https://github.com/Mehuge/Camelot-Unchained/blob/cu-ui-widgets/docs/UI%20Widgets.md)

Lastly it contains some style and other fixes I found with the settings/UI widget code while reorganising stuff.

Some examples of UI dialogs created using these widgets.
https://github.com/Mehuge/Camelot-Unchained/tree/dev/game/hud/src/components/SampleUI

*index.tsx* is a HudNav UI implemented as a stateless component, utilising `HudNavWindow` to handle the events and state around opening and closing.

It randomly opens one of 3 sample dialogs.

*Sample1.tsx* is a `TabbedDialogWithSideMenu` that has both tabs, a side menu and bottom buttons.
*Sample2.tsx* is a `TabbedDialogWithSideMenu` without any tabs or a side menu, or a heading of any kind but does have a bottom button.
*Sample3.tsx* is a `TabbedDialogWithSideMenu` without any tabs or a side menu or bottom buttons.

Using the `TabbedDialog` and `SideMenu` widgets directly allows even more control of how the dialog appears.

### CODE REVIEW

**Comment by Ajackster** [comment]
Can we put these components under the components directory? The plan is to have all re-usable components (Pretty much the things you have under this UI directory and a couple others in components right now) under the components directory. All "end result" widgets (Settings UI, PlayerHealth, GameMenu, etc.) and all of their unique components goes under the widgets directory

**Comment by Mehuge** [comment]
Doh... I got the wrong end of the stick from the Discord chat with JB, re-reading it that is what he said.

Do you mind them being in a UI sub folder?  I ask because of the index re-exporting which makes it more convenient for people to import what they need, or will the components folder become the UI folder and have an index in components that re-exports everything?

**Comment by Mehuge** [comment]
Aware of the conflicts, have them fixed already, but waiting for you to push the library so I can build and test.

**Comment by Ajackster** [comment]
Sure, having a UI subfolder sounds useful, for things that are most re-usable and generic

**Comment by Mehuge** [comment]
Ok, PR rebased and updated so that now Settings is in widgets, and UI is in components.

**Comment by Ajackster** [comment]
Looks good, thanks :) I'll start moving a couple more widgets in the components directory over to widgets/ (PlayerHealth, FriendlyHealth, etc.)

**Pull request merged**
